/**
 * Arena Prime v3.1 — the 12 starter kit specifications (H19).
 *
 * Each kit is a WORKING SITE: home + 6 internal pages + menu + demo content +
 * its own typographic and chromatic preset, mapped to one of the twelve H15
 * pattern families. The homes are specified as distinct structural
 * compositions (AP8: a recoloured skeleton is not a kit), and every kit
 * ships en_US + it_IT content (H42) plus its H21 campaign assets in three
 * aspect ratios.
 *
 * `tools/build-kits.mjs` turns these specs into the installable
 * plugin/arena-engine/kits/<slug>/ payloads consumed by the importer.
 */

export const KITS = [
	{
		slug: 'atelier-mode',
		name: { en_US: 'Atelier Mode', it_IT: 'Atelier Mode' },
		description: 'A slow-fashion atelier: serif editorial home, lookbook journal, made-to-order service.',
		family: 'Editorial',
		preset: 'editorial',
		headerVariant: 'transparent',
		campaign: { cta: { en_US: 'Book a fitting', it_IT: 'Prenota una prova' } },
		home: {
			variant: 'split-serif-hero',
			patterns: [ 'gallery-masonry', 'editorial-timeline', 'newsletter-signup' ],
			eyebrow: { en_US: 'Milano · since 1987', it_IT: 'Milano · dal 1987' },
			title: { en_US: 'Clothes cut once, worn for decades', it_IT: 'Capi tagliati una volta, indossati per decenni' },
			copy: { en_US: 'A twelve-person atelier, natural fibres, and a fitting appointment for every order.', it_IT: 'Un atelier di dodici persone, fibre naturali e una prova su misura per ogni ordine.' },
		},
		pages: [ 'about-atelier', 'contact-appointment', 'faq-care', 'shipping-returns', 'lookbook', 'journal-editorial' ],
		products: [
			{ price: 340, name: { en_US: 'Linen travel coat', it_IT: 'Cappotto di lino da viaggio' }, category: { en_US: 'Outerwear', it_IT: 'Cappotti' }, description: { en_US: 'Unlined linen coat with hand-finished seams.', it_IT: 'Cappotto di lino non foderato con cuciture a mano.' } },
			{ price: 180, name: { en_US: 'Oxford shirt, made to measure', it_IT: 'Camicia Oxford su misura' }, category: { en_US: 'Shirts', it_IT: 'Camicie' }, description: { en_US: 'Egyptian cotton, mother-of-pearl buttons.', it_IT: 'Cotone egiziano, bottoni in madreperla.' } },
			{ price: 460, name: { en_US: 'Pleated wool trousers', it_IT: 'Pantaloni di lana pieghettati' }, category: { en_US: 'Trousers', it_IT: 'Pantaloni' }, description: { en_US: 'High-twist wool that resists creases on trains.', it_IT: 'Lana high-twist che resiste alle pieghe in treno.' } },
			{ price: 95, name: { en_US: 'Silk scarf, archive print', it_IT: 'Foulard di seta, stampa d’archivio' }, category: { en_US: 'Accessories', it_IT: 'Accessori' }, description: { en_US: 'Screen-printed in Como from the 1987 archive.', it_IT: 'Serigrafato a Como dall’archivio 1987.' } },
		],
	},
	{
		slug: 'nordic-furniture',
		name: { en_US: 'Nordic Furniture', it_IT: 'Nordic Furniture' },
		description: 'Flat-pack Scandinavian furniture with a bento-grid home and material-first storytelling.',
		family: 'Discovery',
		preset: 'minimal',
		headerVariant: 'sticky',
		campaign: { cta: { en_US: 'Shop the collection', it_IT: 'Scopri la collezione' } },
		home: {
			variant: 'bento-hero',
			patterns: [ 'category-tiles', 'trust-stats', 'cta-inline-band' ],
			eyebrow: { en_US: 'Birch · steel · wool', it_IT: 'Betulla · acciaio · lana' },
			title: { en_US: 'Furniture that assembles in minutes, lasts for moves', it_IT: 'Mobili che si montano in minuti e sopravvivono ai traslochi' },
			copy: { en_US: 'Flat-packed birch frames, ten-year structural warranty, spare parts forever.', it_IT: 'Strutture in betulla imballate flat, garanzia strutturale dieci anni, ricambi per sempre.' },
		},
		pages: [ 'about-craft', 'contact-showroom', 'faq-assembly', 'shipping-returns', 'materials-guide', 'journal-product' ],
		products: [
			{ price: 690, name: { en_US: 'Fjord bookshelf, 5 bays', it_IT: 'Libreria Fjord, 5 moduli' }, category: { en_US: 'Storage', it_IT: 'Contenitori' }, description: { en_US: 'Birch plywood, tool-free assembly.', it_IT: 'Betulla compensata, montaggio senza attrezzi.' } },
			{ price: 420, name: { en_US: 'Lyng dining table', it_IT: 'Tavolo Lyng' }, category: { en_US: 'Tables', it_IT: 'Tavoli' }, description: { en_US: 'Solid birch top, powder-coated steel legs.', it_IT: 'Piano in betulla massella, gambe in acciaio verniciato.' } },
			{ price: 260, name: { en_US: 'Vik lounge chair', it_IT: 'Poltrona Vik' }, category: { en_US: 'Seating', it_IT: 'Sedute' }, description: { en_US: 'Steam-bent frame with wool bouclé.', it_IT: 'Struttura curvata a vapore con bouclé di lana.' } },
			{ price: 140, name: { en_US: 'Halv side table', it_IT: 'Comodino Halv' }, category: { en_US: 'Tables', it_IT: 'Tavoli' }, description: { en_US: 'The one that survives the bedside chaos.', it_IT: 'Quello che sopravvive al caos del comodino.' } },
			{ price: 89, name: { en_US: 'Skjerm floor lamp', it_IT: 'Piantana Skjerm' }, category: { en_US: 'Lighting', it_IT: 'Illuminazione' }, description: { en_US: 'Opal glass, dimmable warm LED.', it_IT: 'Vetro opalino, LED caldo dimmerabile.' } },
		],
	},
	{
		slug: 'supplement-lab',
		name: { en_US: 'Supplement Lab', it_IT: 'Supplement Lab' },
		description: 'Sports nutrition with lab-tested transparency: data-forward home, batch certificates, subscription refills.',
		family: 'Trust',
		preset: 'commerce',
		headerVariant: 'standard',
		campaign: { cta: { en_US: 'See the lab tests', it_IT: 'Vedi i test di laboratorio' } },
		home: {
			variant: 'data-hero',
			patterns: [ 'social-proof-meters', 'product-grid', 'trust-guarantee' ],
			eyebrow: { en_US: 'Batch-tested · Informed Sport', it_US_note: '', it_IT: 'Testato per batch · Informed Sport' },
			title: { en_US: 'Every scoop, certificate-backed', it_IT: 'Ogni misurino, certificato alla mano' },
			copy: { en_US: 'Third-party assays published per batch. If the label says 5 g of creatine, the lab says 5 g.', it_IT: 'Analisi di terze parti pubblicate per ogni lotto. Se l’etichetta dice 5 g di creatina, il laboratorio dice 5 g.' },
		},
		pages: [ 'about-lab', 'contact-support', 'faq-doping', 'shipping-returns', 'lab-certificates', 'journal-science' ],
		products: [
			{ price: 29, name: { en_US: 'Creatine monohydrate, 500 g', it_IT: 'Creatina monoidrato, 500 g' }, category: { en_US: 'Performance', it_IT: 'Performance' }, description: { en_US: 'Creapure® powder, 100 servings.', it_IT: 'Creapure® in polvere, 100 dosi.' } },
			{ price: 39, name: { en_US: 'Whey isolate, vanilla', it_IT: 'Isolato di siero, vaniglia' }, category: { en_US: 'Protein', it_IT: 'Proteine' }, description: { en_US: '27 g protein per scoop, zero gum fillers.', it_IT: '27 g di proteine per misurino, zero addensanti.' } },
			{ price: 24, name: { en_US: 'Electrolyte sachets, 30 pack', it_IT: 'Stick di elettroliti, 30 pack' }, category: { en_US: 'Hydration', it_IT: 'Idratazione' }, description: { en_US: '1 g sodium for long hot sessions.', it_IT: '1 g di sodio per le sessioni lunghe al caldo.' } },
			{ price: 34, name: { en_US: 'Magnesium glycinate, 90 caps', it_IT: 'Magnesio glicinato, 90 caps' }, category: { en_US: 'Recovery', it_IT: 'Recupero' }, description: { en_US: 'For the sleep that repairs the training.', it_IT: 'Per il sonno che ripara l’allenamento.' } },
		],
	},
	{
		slug: 'specialty-coffee',
		name: { en_US: 'Specialty Coffee Roastery', it_IT: 'Torrefazione di Caffè Specialty' },
		description: 'A roastery with subscription at its core: cover hero, sticky roast story, tiered plans.',
		family: 'Newsletter',
		preset: 'editorial',
		headerVariant: 'transparent',
		campaign: { cta: { en_US: 'Start your subscription', it_IT: 'Avvia l’abbonamento' } },
		home: {
			variant: 'cover-hero-story',
			patterns: [ 'sticky-scroll-story', 'service-membership', 'trust-check-list' ],
			eyebrow: { en_US: 'Roasted Tuesdays, shipped Wednesdays', it_IT: 'Tostato il martedì, spedito il mercoledì' },
			title: { en_US: 'Coffee that arrives still warm with roast', it_IT: 'Un caffè che arriva ancora caldo di tostatura' },
			copy: { en_US: 'Eight origins, one roast profile each, and a postcard from the roaster in every box.', it_IT: 'Otto origini, un profilo di tostatura ciascuna e una cartolina dal tostatore in ogni box.' },
		},
		pages: [ 'about-roastery', 'contact-wholesale', 'faq-brewing', 'shipping-returns', 'origins-guide', 'journal-roast' ],
		products: [
			{ price: 18, name: { en_US: 'Yirgacheffe, washed', it_IT: 'Yirgacheffe, lavato' }, category: { en_US: 'Single origin', it_IT: 'Single origin' }, description: { en_US: 'Jasmine, bergamot, apricot.', it_IT: 'Gelsomino, bergamotto, albicocca.' } },
			{ price: 16, name: { en_US: 'House blend, espresso', it_IT: 'Blend della casa, espresso' }, description: { en_US: 'Cocoa, hazelnut, no bitterness.', it_IT: 'Cacao, nocciola, zero amaro.' }, category: { en_US: 'Blends', it_IT: 'Blend' } },
			{ price: 22, name: { en_US: 'Decaf, sugarcane process', it_IT: 'Decaffeinato, processo alla canna' }, category: { en_US: 'Single origin', it_IT: 'Single origin' }, description: { en_US: 'All the comfort, none of the jitters.', it_IT: 'Tutto il comfort, nessun tremore.' } },
			{ price: 48, name: { en_US: 'Brew kit, V60 starter', it_IT: 'Kit di preparazione, V60 starter' }, category: { en_US: 'Gear', it_IT: 'Attrezzatura' }, description: { en_US: 'Dripper, filters, 340 g of the house blend.', it_IT: 'Dripper, filtri, 340 g del blend di casa.' } },
		],
	},
	{
		slug: 'tech-refurb',
		name: { en_US: 'Tech Refurb Depot', it_IT: 'Tech Refurb Depot' },
		description: 'Refurbished electronics with honest grading: comparison tables, warranty tiers, step-by-step support.',
		family: 'Product',
		preset: 'commerce',
		headerVariant: 'sticky',
		campaign: { cta: { en_US: 'Shop graded stock', it_IT: 'Vedi il lotto graduato' } },
		home: {
			variant: 'compare-hero',
			patterns: [ 'support-steps', 'reviews-compact', 'cta-banner' ],
			eyebrow: { en_US: 'Grade A → C, priced honestly', it_IT: 'Grado A → C, prezzi onesti' },
			title: { en_US: 'Last year’s flagship, this year’s price', it_IT: 'Il top di gamma dell’anno scorso al prezzo di quest’anno' },
			copy: { en_US: 'Every unit photographed, battery-health printed, 24-month warranty on Grade A.', it_IT: 'Ogni unità fotografata, salute batteria dichiarata, garanzia 24 mesi sul Grado A.' },
		},
		pages: [ 'about-refurb', 'contact-support', 'faq-grades', 'shipping-returns', 'warranty-tiers', 'journal-refurb' ],
		products: [
			{ price: 689, name: { en_US: '13" ultrabook, Grade A', it_IT: 'Ultrabook 13", Grado A' }, category: { en_US: 'Laptops', it_IT: 'Portatili' }, description: { en_US: 'Battery 94%, original charger, 24-month warranty.', it_IT: 'Batteria 94%, caricatore originale, garanzia 24 mesi.' } },
			{ price: 349, name: { en_US: 'Flagship phone, Grade B', it_IT: 'Smartphone top di gamma, Grado B' }, category: { en_US: 'Phones', it_IT: 'Smartphone' }, description: { en_US: 'Micro-scratches on the frame, flawless screen.', it_IT: 'Micro-graffi sulla scocca, vetro impeccabile.' } },
			{ price: 199, name: { en_US: 'Tablet 11", Grade C', it_IT: 'Tablet 11", Grado C' }, category: { en_US: 'Tablets', it_IT: 'Tablet' }, description: { en_US: 'Visible dents, spotless display, works perfectly.', it_IT: 'Ammaccature visibili, display pulito, funziona perfettamente.' } },
			{ price: 129, name: { en_US: 'Noise-cancelling headphones', it_IT: 'Cuffie con cancellazione attiva' }, category: { en_US: 'Audio', it_IT: 'Audio' }, description: { en_US: 'New pads, refurbished drivers, 12-month warranty.', it_IT: 'Padiglioni nuovi, driver rigenerati, garanzia 12 mesi.' } },
		],
	},
	{
		slug: 'ceramic-studio',
		name: { en_US: 'Ceramic Studio', it_IT: 'Studio Ceramico' },
		description: 'A working pottery studio: gallery-first home, workshop bookings, one-of-a-kind pieces.',
		family: 'Gallery',
		preset: 'soft',
		headerVariant: 'standard',
		campaign: { cta: { en_US: 'Take a workshop', it_IT: 'Prenota un corso' } },
		home: {
			variant: 'gallery-hero',
			patterns: [ 'hero-stack-copy', 'testimonials-scroller', 'newsletter-confirm' ],
			eyebrow: { en_US: 'Stoneware · wood-fired', it_IT: 'Gres · cottura a legna' },
			title: { en_US: 'Plates that make dinner feel like Sunday', it_IT: 'Piatti che fanno sembrare la cena una domenica' },
			copy: { en_US: 'Each piece thrown, glazed and signed in the studio. No two identical, none dishwasher-shy.', it_IT: 'Ogni pezzo tornito, smaltato e firmato in studio. Nessuno identico, tutti lavabili in lavastoviglie.' },
		},
		pages: [ 'about-studio', 'contact-workshop', 'faq-care', 'shipping-returns', 'collections-glazes', 'journal-kiln' ],
		products: [
			{ price: 42, name: { en_US: 'Dinner plate, ash glaze', it_IT: 'Piatto piano, smalto cenere' }, category: { en_US: 'Tableware', it_IT: 'Stoviglie' }, description: { en_US: '27 cm, stackable, oven-safe.', it_IT: '27 cm, impilabile, adatto al forno.' } },
			{ price: 58, name: { en_US: 'Mug, thumb rest', it_IT: 'Tazza con appoggia-pollice' }, category: { en_US: 'Tableware', it_IT: 'Stoviglie' }, description: { en_US: '350 ml that keeps coffee hot to the last sip.', it_IT: '350 ml che mantengono il caffè caldo fino all’ultimo sorso.' } },
			{ price: 120, name: { en_US: 'Vase, tall bottle form', it_IT: 'Vaso, forma bottiglia alta' }, category: { en_US: 'Objects', it_IT: 'Oggetti' }, description: { en_US: 'One branch of eucalyptus is enough.', it_IT: 'Basta un ramo di eucalipto.' } },
			{ price: 240, name: { en_US: 'Teapot with cups, set of 5', it_IT: 'Teiera con tazze, set di 5' }, category: { en_US: 'Objects', it_IT: 'Oggetti' }, description: { en_US: 'The gift that outlives the occasion.', it_IT: 'Il regalo che sopravvive all’occasione.' } },
		],
	},
	{
		slug: 'outdoor-depot',
		name: { en_US: 'Outdoor Depot', it_IT: 'Outdoor Depot' },
		description: 'A gear depot for weekend alpinists: category-first navigation, carousel highlights, hard guarantees.',
		family: 'Hero',
		preset: 'commerce',
		headerVariant: 'sticky',
		campaign: { cta: { en_US: 'Gear up', it_IT: 'Equipaggiati' } },
		home: {
			variant: 'catalog-hero',
			patterns: [ 'category-tiles', 'carousel-showcase', 'product-grid', 'trust-bar' ],
			eyebrow: { en_US: 'Free returns on boots, always', it_IT: 'Resi gratuiti sugli scarponi, sempre' },
			title: { en_US: 'The summit is optional. The right gear is not.', it_IT: 'La vetta è opzionale. L’attrezzatura giusta no.' },
			copy: { en_US: 'Boots, shells and packs tested by our guides on the mountains you are actually going to climb.', it_IT: 'Scarponi, shell e zaini testati dalle nostre guide sulle montagne che scalerai davvero.' },
		},
		pages: [ 'about-guides', 'contact-experts', 'faq-sizing', 'shipping-returns', 'gear-checklists', 'journal-routes' ],
		products: [
			{ price: 219, name: { en_US: 'Trail boots, waterproof', it_IT: 'Scarponi da trail, impermeabili' }, category: { en_US: 'Footwear', it_IT: 'Calzature' }, description: { en_US: 'Broken in by the third kilometre.', it_IT: 'Rodati al terzo chilometro.' } },
			{ price: 279, name: { en_US: '3-layer shell jacket', it_IT: 'Giacca shell 3 strati' }, category: { en_US: 'Clothing', it_IT: 'Abbigliamento' }, description: { en_US: 'Twenty-thousand-millimetre column, 310 g.', it_IT: 'Colonna d’acqua ventimila, 310 g.' } },
			{ price: 149, name: { en_US: '45 L alpine pack', it_IT: 'Zaino alpino 45 L' }, category: { en_US: 'Packs', it_IT: 'Zaini' }, description: { en_US: 'Rope strap, axe loop, Sunday-comfort hip belt.', it_IT: 'Portacorda, portapicco, fascia lombare da domenica.' } },
			{ price: 59, name: { en_US: 'Merino base layer', it_IT: 'Strato base in merino' }, category: { en_US: 'Clothing', it_IT: 'Abbigliamento' }, description: { en_US: 'Wear it three days; your tent-mate won’t notice.', it_IT: 'Indossalo tre giorni: il compagno di tenda non se ne accorgerà.' } },
			{ price: 19, name: { en_US: 'Headlamp, 400 lm', it_IT: 'Frontale, 400 lm' }, category: { en_US: 'Gear', it_IT: 'Attrezzatura' }, description: { en_US: 'The one piece you forget until you need it.', it_IT: 'L’unico pezzo che dimentichi finché non serve.' } },
		],
	},
	{
		slug: 'beauty-ritual',
		name: { en_US: 'Beauty Ritual', it_IT: 'Beauty Ritual' },
		description: 'Slow skincare with a three-step ritual: soft hero, podium products, ritual cards newsletter.',
		family: 'Conversion',
		preset: 'soft',
		headerVariant: 'transparent',
		campaign: { cta: { en_US: 'Build your ritual', it_IT: 'Costruisci il rituale' } },
		home: {
			variant: 'ritual-hero',
			patterns: [ 'product-feature-podium', 'newsletter-cards', 'editorial-quote-strip' ],
			eyebrow: { en_US: 'Three steps, five minutes', it_IT: 'Tre passi, cinque minuti' },
			title: { en_US: 'Skincare with an off switch at 9 p.m.', it_IT: 'La skincare con lo spegnimento alle 21' },
			copy: { en_US: 'Cleanse, treat, seal. Fourteen ingredients per bottle, all of them pronounceable.', it_IT: 'Detergere, trattare, sigillare. Quattordici ingredienti per flacone, tutti pronunciabili.' },
		},
		pages: [ 'about-ritual', 'contact-consult', 'faq-skin', 'shipping-returns', 'ingredients-glossary', 'journal-skin' ],
		products: [
			{ price: 26, name: { en_US: 'Cleansing balm, 100 ml', it_IT: 'Balsamo detergente, 100 ml' }, category: { en_US: 'Step 1 · Cleanse', it_IT: 'Passo 1 · Detergere' }, description: { en_US: 'Melts sunscreen, respects the barrier.', it_IT: 'Scioglie la crema solare, rispetta la barriera.' } },
			{ price: 38, name: { en_US: 'Niacinamide 5% serum', it_IT: 'Siero niacinamide 5%' }, category: { en_US: 'Step 2 · Treat', it_IT: 'Passo 2 · Trattare' }, description: { en_US: 'For pores that gossip.', it_IT: 'Per i pori che spettegolano.' } },
			{ price: 32, name: { en_US: 'Ceramide night cream', it_IT: 'Crema notte alla ceramide' }, category: { en_US: 'Step 3 · Seal', it_IT: 'Passo 3 · Sigillare' }, description: { en_US: 'The lock on the door.', it_IT: 'La serratura sulla porta.' } },
			{ price: 18, name: { en_US: 'SPF 50 morning fluid', it_IT: 'Fluido SPF 50 da giorno' }, category: { en_US: 'Morning', it_IT: 'Mattina' }, description: { en_US: 'No white cast, no excuses.', it_IT: 'Niente velo bianco, nessuna scusa.' } },
		],
	},
	{
		slug: 'bookshop',
		name: { en_US: 'Independent Bookshop', it_IT: 'Libreria Indipendente' },
		description: 'A neighbourhood bookshop online: magazine home, staff picks, events calendar, A–Z index.',
		family: 'Editorial',
		preset: 'magazine',
		headerVariant: 'standard',
		campaign: { cta: { en_US: 'Reserve for pickup', it_IT: 'Prenota e ritira' } },
		home: {
			variant: 'magazine-hero',
			patterns: [ 'case-study-quote', 'product-editorial-grid', 'quick-links-list' ],
			eyebrow: { en_US: 'Open until 21:00, dogs welcome', it_IT: 'Aperti fino alle 21:00, cani benvenuti' },
			title: { en_US: 'The table at the front, curated every Friday', it_IT: 'Il tavolo all’ingresso, curato ogni venerdì' },
			copy: { en_US: 'Five staff members, five honest opinions, zero algorithms. Reserve online, pick up with a coffee.', it_IT: 'Cinque librai, cinque opinioni oneste, zero algoritmi. Prenota online, ritira con un caffè.' },
		},
		pages: [ 'about-bookshop', 'contact-events', 'faq-orders', 'shipping-returns', 'events-calendar', 'journal-picks' ],
		products: [
			{ price: 18, name: { en_US: 'Staff pick of the month', it_IT: 'Scelta del mese dello staff' }, category: { en_US: 'Fiction', it_IT: 'Narrativa' }, description: { en_US: 'Wrapped in brown paper with a handwritten note.', it_IT: 'Incartato in carta kraft con un biglietto a mano.' } },
			{ price: 24, name: { en_US: 'Subscription: a book a month', it_IT: 'Abbonamento: un libro al mese' }, category: { en_US: 'Subscriptions', it_IT: 'Abbonamenti' }, description: { en_US: 'Chosen by a human who reads your last three picks.', it_IT: 'Scelto da un umano che legge i tuoi ultimi tre titoli.' } },
			{ price: 32, name: { en_US: 'City map, illustrated', it_IT: 'Mappa della città, illustrata' }, category: { en_US: 'Maps', it_IT: 'Mappe' }, description: { en_US: 'The one locals gift to visitors.', it_IT: 'Quella che i locali regalano ai visitatori.' } },
			{ price: 14, name: { en_US: 'Notebook, staff-designed', it_IT: 'Taccuino, disegnato dallo staff' }, category: { en_US: 'Stationery', it_IT: 'Cancelleria' }, description: { en_US: 'Margins wide enough for arguments.', it_IT: 'Margini abbastanza larghi per le discussioni.' } },
		],
	},
	{
		slug: 'pet-supply',
		name: { en_US: 'Pet Supply Co.', it_IT: 'Pet Supply Co.' },
		description: 'Loud, honest pet food: bold cover hero, portion calculator, countdown offers, before/after coats.',
		family: 'Support',
		preset: 'brutal',
		headerVariant: 'standard',
		campaign: { cta: { en_US: 'Feed them better', it_IT: 'Nutrili meglio' } },
		home: {
			variant: 'bold-cover-hero',
			patterns: [ 'feature-bento', 'cta-countdown', 'gallery-compare' ],
			eyebrow: { en_US: 'Meat first. Always.', it_IT: 'Carne prima. Sempre.' },
			title: { en_US: 'Dog food with nothing to hide', it_IT: 'Cibo per cani senza nulla da nascondere' },
			copy: { en_US: 'Sixty percent meat, zero fillers, and the full recipe printed on the front. Yes, the front.', it_IT: 'Sessanta per cento carne, zero filler e la ricetta completa stampata sul fronte. Sì, sul fronte.' },
		},
		pages: [ 'about-kitchen', 'contact-pack', 'faq-portions', 'shipping-returns', 'breed-guide', 'journal-pack' ],
		products: [
			{ price: 46, name: { en_US: 'Adult dry food, 12 kg', it_IT: 'Crocchette adulto, 12 kg' }, category: { en_US: 'Dry food', it_IT: 'Crocchette' }, description: { en_US: '60% lamb, the bag says so in 40-point type.', it_IT: '60% agnello, la confezione lo dichiara in corpo 40.' } },
			{ price: 32, name: { en_US: 'Wet trays, 12 pack', it_IT: 'Vaschette umido, 12 pack' }, category: { en_US: 'Wet food', it_IT: 'Umido' }, description: { en_US: 'The spoon-licking one.', it_IT: 'Quella da leccarsi il cucchiaio.' } },
			{ price: 14, name: { en_US: 'Dental sticks, 28 pack', it_IT: 'Stick dentali, 28 pack' }, category: { en_US: 'Treats', it_IT: 'Snack' }, description: { en_US: 'Negotiation-grade. Breath fixed.', it_IT: 'Grado da negoziazione. Alito sistemato.' } },
			{ price: 22, name: { en_US: 'Puppy starter kit', it_IT: 'Kit cucciolo' }, category: { en_US: 'Kits', it_IT: 'Kit' }, description: { en_US: 'Everything for the first forty days.', it_IT: 'Tutto per i primi quaranta giorni.' } },
		],
	},
	{
		slug: 'bike-service',
		name: { en_US: 'Bike Service Workshop', it_IT: 'Officina Bike Service' },
		description: 'A service business home: booking-first split hero, live workshop status, transparent repair tiers.',
		family: 'Service',
		preset: 'minimal',
		headerVariant: 'standard',
		campaign: { cta: { en_US: 'Book a service', it_IT: 'Prenota un intervento' } },
		home: {
			variant: 'service-hero',
			patterns: [ 'support-tiles', 'service-status', 'cta-split-panel' ],
			eyebrow: { en_US: 'Same-week slots · loaner bikes', it_IT: 'Slot nella stessa settimana · bici prestito' },
			title: { en_US: 'The workshop that texts you before you ask', it_IT: 'L’officina che ti scrive prima che tu chieda' },
			copy: { en_US: 'Book online, drop the bike, get photo updates at every step. No surprises on the invoice, ever.', it_IT: 'Prenota online, lascia la bici, ricevi aggiornamenti con foto a ogni passaggio. Zero sorprese in fattura.' },
		},
		pages: [ 'about-workshop', 'contact-booking', 'faq-repairs', 'shipping-returns', 'service-price-list', 'journal-mechanics' ],
		products: [
			{ price: 89, name: { en_US: 'Basic service, tier 1', it_IT: 'Manutenzione base, livello 1' }, category: { en_US: 'Services', it_IT: 'Servizi' }, description: { en_US: 'Gears, brakes, torque check, wash.', it_IT: 'Cambio, freni, controllo coppie, lavaggio.' } },
			{ price: 159, name: { en_US: 'Full service, tier 2', it_IT: 'Manutenzione completa, livello 2' }, category: { en_US: 'Services', it_IT: 'Servizi' }, description: { en_US: 'Tier 1 plus hub service and wheel true.', it_IT: 'Livello 1 più mozzi e centratura ruote.' } },
			{ price: 39, name: { en_US: 'Flat-fix, while-you-wait', it_IT: 'Riparazione foratura, in attesa' }, category: { en_US: 'Services', it_IT: 'Servizi' }, description: { en_US: 'Fifteen minutes, coffee included.', it_IT: 'Quindici minuti, caffè incluso.' } },
			{ price: 25, name: { en_US: 'Winter storage, per month', it_IT: 'Deposito invernale, al mese' }, category: { en_US: 'Services', it_IT: 'Servizi' }, description: { en_US: 'Heated room, monthly charge, spring tune-up discount.', it_IT: 'Stanza riscaldata, carica mensile, sconto sulla messa a punto primaverile.' } },
		],
	},
	{
		slug: 'digital-assets',
		name: { en_US: 'Digital Assets Store', it_IT: 'Digital Assets Store' },
		description: 'Minimal storefront for digital goods: quiet hero, instant delivery, no-distraction checkout.',
		family: 'Checkout',
		preset: 'minimal',
		headerVariant: 'standard',
		campaign: { cta: { en_US: 'Download instantly', it_IT: 'Scarica subito' } },
		home: {
			variant: 'quiet-hero',
			patterns: [ 'product-grid', 'faq-accordion', 'cta-inline-band' ],
			eyebrow: { en_US: 'Instant download · lifetime updates', it_IT: 'Download immediato · aggiornamenti a vita' },
			title: { en_US: 'Fonts, templates and kits that respect deadlines', it_IT: 'Font, template e kit che rispettano le deadline' },
			copy: { en_US: 'Buy once at 9:41, ship the deck by 10:00. Commercial licenses included, no subscriptions.', it_IT: 'Compra alle 9:41, consegna la presentazione alle 10:00. Licenze commerciali incluse, zero abbonamenti.' },
		},
		pages: [ 'about-studio', 'contact-support', 'faq-licenses', 'shipping-returns', 'license-guide', 'journal-design' ],
		products: [
			{ price: 49, name: { en_US: 'Grotesk family, 9 styles', it_IT: 'Famiglia Grotesk, 9 stili' }, category: { en_US: 'Fonts', it_IT: 'Font' }, description: { en_US: 'Variable, hinted, desktop + web license.', it_IT: 'Variabile, hintata, licenza desktop + web.' } },
			{ price: 29, name: { en_US: 'Pitch deck template, 120 slides', it_IT: 'Template pitch deck, 120 slide' }, category: { en_US: 'Templates', it_IT: 'Template' }, description: { en_US: 'For the meeting that decides budgets.', it_IT: 'Per la riunione che decide i budget.' } },
			{ price: 39, name: { en_US: 'Icon set, 480 icons', it_IT: 'Set icone, 480 icone' }, category: { en_US: 'Icons', it_IT: 'Icone' }, description: { en_US: 'Consistent 2 px grid, SVG + Figma.', it_IT: 'Griglia coerente a 2 px, SVG + Figma.' } },
			{ price: 19, name: { en_US: 'Invoice kit for freelancers', it_IT: 'Kit fatture per freelance' }, description: { en_US: 'Look paid, get paid.', it_IT: 'Sembra professionale, viene pagato.' }, category: { en_US: 'Templates', it_IT: 'Template' } },
		],
	},
];

/**
 * Internal page types with 3 structural variants each (AP8).
 *
 * Each builder returns block markup using {{t:…}} tokens resolved at import.
 */
export const PAGE_TYPES = {
	'about-atelier':      { type: 'about', variant: 0, title: { en_US: 'The atelier', it_IT: 'L’atelier' } },
	'about-craft':        { type: 'about', variant: 1, title: { en_US: 'How we build', it_IT: 'Come costruiamo' } },
	'about-lab':          { type: 'about', variant: 2, title: { en_US: 'The lab', it_IT: 'Il laboratorio' } },
	'about-roastery':     { type: 'about', variant: 0, title: { en_US: 'The roastery', it_IT: 'La torrefazione' } },
	'about-refurb':       { type: 'about', variant: 1, title: { en_US: 'What refurb means here', it_IT: 'Cosa significa ricondizionato qui' } },
	'about-studio':       { type: 'about', variant: 2, title: { en_US: 'The studio', it_IT: 'Lo studio' } },
	'about-guides':       { type: 'about', variant: 0, title: { en_US: 'Our guides', it_IT: 'Le nostre guide' } },
	'about-ritual':       { type: 'about', variant: 1, title: { en_US: 'The ritual', it_IT: 'Il rituale' } },
	'about-bookshop':     { type: 'about', variant: 2, title: { en_US: 'The bookshop', it_IT: 'La libreria' } },
	'about-kitchen':      { type: 'about', variant: 0, title: { en_US: 'Our kitchen', it_IT: 'La nostra cucina' } },
	'about-workshop':     { type: 'about', variant: 1, title: { en_US: 'The workshop', it_IT: 'L’officina' } },
	'about-studio-d':     { type: 'about', variant: 2, title: { en_US: 'The studio', it_IT: 'Lo studio' } },

	'contact-appointment': { type: 'contact', variant: 0, title: { en_US: 'Book a fitting', it_IT: 'Prenota una prova' } },
	'contact-showroom':   { type: 'contact', variant: 1, title: { en_US: 'Visit the showroom', it_IT: 'Visita lo showroom' } },
	'contact-support':    { type: 'contact', variant: 2, title: { en_US: 'Talk to us', it_IT: 'Parla con noi' } },
	'contact-wholesale':  { type: 'contact', variant: 0, title: { en_US: 'Wholesale', it_IT: 'Vendita all’ingrosso' } },
	'contact-experts':    { type: 'contact', variant: 1, title: { en_US: 'Ask a guide', it_IT: 'Chiedi a una guida' } },
	'contact-consult':    { type: 'contact', variant: 2, title: { en_US: 'Skin consult', it_IT: 'Consulenza pelle' } },
	'contact-events':     { type: 'contact', variant: 0, title: { en_US: 'Events & readings', it_IT: 'Eventi e letture' } },
	'contact-pack':       { type: 'contact', variant: 1, title: { en_US: 'Write to the pack', it_IT: 'Scrivi al branco' } },
	'contact-booking':    { type: 'contact', variant: 2, title: { en_US: 'Book a service', it_IT: 'Prenota un intervento' } },
	'contact-workshop':   { type: 'contact', variant: 2, title: { en_US: 'Workshops', it_IT: 'Corsi' } },

	'faq-care':     { type: 'faq', variant: 0, title: { en_US: 'Care & repairs', it_IT: 'Cura e riparazioni' } },
	'faq-assembly': { type: 'faq', variant: 1, title: { en_US: 'Assembly', it_IT: 'Montaggio' } },
	'faq-doping':   { type: 'faq', variant: 2, title: { en_US: 'Testing & sport', it_IT: 'Test e sport' } },
	'faq-brewing':  { type: 'faq', variant: 0, title: { en_US: 'Brewing', it_IT: 'Preparazione' } },
	'faq-grades':   { type: 'faq', variant: 1, title: { en_US: 'Grades explained', it_IT: 'I gradi spiegati' } },
	'faq-sizing':   { type: 'faq', variant: 2, title: { en_US: 'Sizing & fit', it_IT: 'Taglie e calzata' } },
	'faq-skin':     { type: 'faq', variant: 0, title: { en_US: 'Skin questions', it_IT: 'Domande sulla pelle' } },
	'faq-orders':   { type: 'faq', variant: 1, title: { en_US: 'Orders & pickup', it_IT: 'Ordini e ritiro' } },
	'faq-portions': { type: 'faq', variant: 2, title: { en_US: 'Portions', it_IT: 'Porzioni' } },
	'faq-repairs':  { type: 'faq', variant: 0, title: { en_US: 'Repairs', it_IT: 'Riparazioni' } },
	'faq-licenses': { type: 'faq', variant: 1, title: { en_US: 'Licenses', it_IT: 'Licenze' } },

	'shipping-returns': { type: 'legal', variant: 0, title: { en_US: 'Shipping & returns', it_IT: 'Spedizioni e resi' } },

	'lookbook':            { type: 'collection', variant: 0, title: { en_US: 'Lookbook', it_IT: 'Lookbook' } },
	'materials-guide':     { type: 'collection', variant: 1, title: { en_US: 'Materials guide', it_IT: 'Guida ai materiali' } },
	'lab-certificates':    { type: 'collection', variant: 2, title: { en_US: 'Lab certificates', it_IT: 'Certificati di laboratorio' } },
	'origins-guide':       { type: 'collection', variant: 0, title: { en_US: 'Origins', it_IT: 'Origini' } },
	'warranty-tiers':      { type: 'collection', variant: 1, title: { en_US: 'Warranty tiers', it_IT: 'Livelli di garanzia' } },
	'collections-glazes':  { type: 'collection', variant: 2, title: { en_US: 'Glazes', it_IT: 'Smalti' } },
	'gear-checklists':     { type: 'collection', variant: 0, title: { en_US: 'Gear checklists', it_IT: 'Checklist attrezzatura' } },
	'ingredients-glossary':{ type: 'collection', variant: 1, title: { en_US: 'Ingredients glossary', it_IT: 'Glossario ingredienti' } },
	'events-calendar':     { type: 'collection', variant: 2, title: { en_US: 'Events', it_IT: 'Eventi' } },
	'breed-guide':         { type: 'collection', variant: 0, title: { en_US: 'Breed guide', it_IT: 'Guida alle razze' } },
	'service-price-list':  { type: 'collection', variant: 1, title: { en_US: 'Price list', it_IT: 'Listino' } },
	'license-guide':       { type: 'collection', variant: 2, title: { en_US: 'License guide', it_IT: 'Guida alle licenze' } },

	'journal-editorial': { type: 'journal', variant: 0, title: { en_US: 'Journal', it_IT: 'Diario' } },
	'journal-product':   { type: 'journal', variant: 1, title: { en_US: 'Notes on making', it_IT: 'Appunti di produzione' } },
	'journal-science':   { type: 'journal', variant: 2, title: { en_US: 'Science notes', it_IT: 'Note scientifiche' } },
	'journal-roast':     { type: 'journal', variant: 0, title: { en_US: 'Roast log', it_IT: 'Diario di tostatura' } },
	'journal-refurb':    { type: 'journal', variant: 1, title: { en_US: 'Bench notes', it_IT: 'Note dal banco' } },
	'journal-kiln':      { type: 'journal', variant: 2, title: { en_US: 'Kiln diary', it_IT: 'Diario del forno' } },
	'journal-routes':    { type: 'journal', variant: 0, title: { en_US: 'Routes', it_IT: 'Itinerari' } },
	'journal-skin':      { type: 'journal', variant: 1, title: { en_US: 'Skin notes', it_IT: 'Note sulla pelle' } },
	'journal-picks':     { type: 'journal', variant: 2, title: { en_US: 'Staff picks', it_IT: 'Scelte dello staff' } },
	'journal-pack':      { type: 'journal', variant: 0, title: { en_US: 'From the pack', it_IT: 'Dal branco' } },
	'journal-mechanics': { type: 'journal', variant: 1, title: { en_US: 'Workshop notes', it_IT: 'Note dall’officina' } },
	'journal-design':    { type: 'journal', variant: 2, title: { en_US: 'Design notes', it_IT: 'Note di design' } },
};
