#!/usr/bin/env node
/**
 * Arena Prime v3.1 — H41 RTL stylesheet builder.
 *
 * Generates `<name>-rtl.css` next to every theme stylesheet (global + each
 * H45 module). The output replaces the LTR file when `is_rtl()` — see
 * Assets::style_src(), which swaps the URL explicitly on the RTL branch.
 *
 * Strategy, in order:
 *   1. Logical properties pass through untouched (most of the codebase is
 *      already written with margin-inline / inset-inline / border-start).
 *   2. Physical properties are mirrored: left↔right (margin, padding,
 *      border-*, top-left/top-right radius, clear, float, left/right inset),
 *      text-align values, and translateX() signs inside transform.
 *   3. Anything that cannot be mirrored safely (grid templates, keyframe
 *      names, custom property names) is left alone.
 *
 * Run: node tools/build-rtl.mjs
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, basename } from 'node:path';

const ROOT = process.cwd();
const CSS_DIR = join( ROOT, 'theme', 'arena-commerce', 'assets', 'css' );
const MODULES = join( CSS_DIR, 'modules' );

/** Physical property → mirrored property. */
const MIRROR = {
	'margin-left': 'margin-right',
	'margin-right': 'margin-left',
	'padding-left': 'padding-right',
	'padding-right': 'padding-left',
	'border-left': 'border-right',
	'border-right': 'border-left',
	'border-left-width': 'border-right-width',
	'border-right-width': 'border-left-width',
	'border-left-style': 'border-right-style',
	'border-right-style': 'border-left-style',
	'border-left-color': 'border-right-color',
	'border-right-color': 'border-left-color',
	'border-top-left-radius': 'border-top-right-radius',
	'border-top-right-radius': 'border-top-left-radius',
	'border-bottom-left-radius': 'border-bottom-right-radius',
	'border-bottom-right-radius': 'border-bottom-left-radius',
	'border-start-start-radius': 'border-start-end-radius',
	'border-start-end-radius': 'border-start-start-radius',
	'border-end-start-radius': 'border-end-end-radius',
	'border-end-end-radius': 'border-end-start-radius',
	'left': 'right',
	'right': 'left',
	'float': 'float',
	'clear': 'clear',
	'text-align': 'text-align',
	'transform': 'transform',
	'translate': 'translate',
};

const MIRROR_VALUES = {
	float: { left: 'right', right: 'left' },
	clear: { left: 'right', right: 'left' },
	'text-align': { left: 'right', right: 'left', start: 'end', end: 'start' },
};

function flipDeclaration( prop, value ) {
	if ( ! Object.prototype.hasOwnProperty.call( MIRROR, prop ) ) {
		return null; /* logical or direction-agnostic. */
	}

	if ( MIRROR_VALUES[ prop ] ) {
		const flipped = value.replace( /\b(left|right|start|end)\b/g, ( word ) => MIRROR_VALUES[ prop ][ word ] || word );
		return `${ MIRROR[ prop ] }: ${ flipped }`;
	}

	if ( prop === 'transform' || prop === 'translate' ) {
		const flipped = value.replace(
			/translateX\(\s*(-?\d+(?:\.\d+)?(?:px|rem|em|%)?)\s*\)/g,
			( match, magnitude ) => magnitude.trim().startsWith( '-' ? match : '' )
		);
		/* Sign-flip the X translation. */
		const signFlipped = value.replace(
			/translateX\(\s*(-?)([\d.]+)(px|rem|em|%|vw)?\s*\)/g,
			( _m, sign, num, unit ) => `translateX(${ sign === '-' ? '' : '-' }${ num }${ unit || 'px' })`
		);
		return `${ prop }: ${ signFlipped || flipped }`;
	}

	return `${ MIRROR[ prop ] }: ${ value }`;
}

function buildRtl( css ) {
	return css.replace( /(^|})([^{}@]*)(\{[^{}]*\})/g, ( match, brace, selector, block ) => {
		const flipped = block.replace( /([a-z-]+)\s*:\s*([^;]+);/g, ( _decl, prop, value ) => {
			const mirrored = flipDeclaration( prop.trim(), value.trim() );

			return mirrored ? `${ mirrored };` : `${ prop }: ${ value };`;
		} );

		return `${ brace }${ selector }${ flipped }`;
	} );
}

function processFile( file ) {
	const css = readFileSync( file, 'utf8' );
	const rtl = buildRtl( css );
	const out = file.replace( /\.css$/, '-rtl.css' );

	writeFileSync( out, `/*! GENERATED by tools/build-rtl.mjs — H41. Do not edit by hand; rerun the tool. */\n${ rtl }` );
	console.log( `[rtl] ${ basename( file ) } → ${ basename( out ) }` );
}

processFile( join( CSS_DIR, 'arena.css' ) );

for ( const file of readdirSync( MODULES ) ) {
	if ( file.endsWith( '.css' ) && ! file.endsWith( '-rtl.css' ) ) {
		processFile( join( MODULES, file ) );
	}
}

console.log( '\n[rtl] done. Enqueued conditionally on is_rtl() by Assets::style_src() (H41).' );
